# Generated by Django 2.0.5 on 2018-07-16 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicule',
            old_name='Type_vehicule',
            new_name='type_vehicule',
        ),
    ]
