# Generated by Django 2.0.5 on 2018-07-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statut',
            name='libelle_statut',
        ),
        migrations.RemoveField(
            model_name='typevehicule',
            name='libelle_type_vehicule',
        ),
        migrations.AddField(
            model_name='statut',
            name='Statut',
            field=models.CharField(choices=[('VF', 'ValidationFormateur'), ('AF', 'AttenteFormateur'), ('RF', 'RefusFormateur'), ('AD', 'AttenteDevis'), ('VC', 'ValidationClient'), ('AC', 'AttenteClient'), ('RC', 'RefusClient')], default='AF', max_length=20),
        ),
        migrations.AddField(
            model_name='typevehicule',
            name='Type_vehicule',
            field=models.CharField(choices=[('voiture', 'Voiture'), ('moto', 'Moto'), ('velo', 'Velo')], default='voiture', max_length=10),
        ),
    ]
