# Generated by Django 2.0.7 on 2018-07-16 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.TextField(max_length=50, verbose_name='Nom de la rue')),
                ('street_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Numéro de la rue')),
                ('street_complement', models.CharField(blank=True, max_length=50, null=True, verbose_name="Complément d'adresse")),
            ],
            options={
                'verbose_name': 'Adresse',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=25, verbose_name='Ville')),
            ],
            options={
                'verbose_name': 'Ville',
            },
        ),
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.IntegerField(verbose_name='Code Postal')),
            ],
            options={
                'verbose_name': 'Code Postal',
                'verbose_name_plural': 'Codes Postaux',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='zipCode',
            field=models.ManyToManyField(to='garage.ZipCode', verbose_name='Code Postal'),
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.City', verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='address',
            name='zipCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.ZipCode', verbose_name='Code Postal'),
        ),
    ]
