# Generated by Django 2.0.5 on 2018-07-11 07:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_type_vehicule', models.CharField(max_length=10, verbose_name='type de véhicule')),
            ],
        ),
        migrations.AddField(
            model_name='motorise',
            name='carte_assurance_img',
            field=models.ImageField(blank=True, null=True, upload_to='img/carte_assurance', verbose_name='carte assurance'),
        ),
        migrations.AddField(
            model_name='motorise',
            name='carte_grise_img',
            field=models.ImageField(blank=True, null=True, upload_to='img/carte_grise', verbose_name='carte grise'),
        ),
        migrations.AddField(
            model_name='motorise',
            name='date_mec',
            field=models.DateField(default=datetime.datetime.now, null=True, verbose_name='date de première m.e.c.'),
        ),
        migrations.AddField(
            model_name='motorise',
            name='immatriculation',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='motorise',
            name='kilometrage',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='motorise',
            name='vin',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='motorise',
            name='libelle_marque',
            field=models.CharField(max_length=100, null=True, verbose_name='libellé marque'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='libelle_modele',
            field=models.CharField(max_length=50, verbose_name='libellé modèle'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='type_vehicule',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='garage.Type'),
            preserve_default=False,
        ),
    ]
