# Generated by Django 2.0.5 on 2018-07-16 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0002_auto_20180716_1551'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TypeVehicule',
        ),
        migrations.RemoveField(
            model_name='vehicule',
            name='Type_vehicule',
        ),
    ]
