# Generated by Django 2.0.5 on 2018-07-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0002_auto_20180716_1714'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Statut',
        ),
        migrations.AddField(
            model_name='devis',
            name='Statut',
            field=models.CharField(choices=[('VF', 'ValidationFormateur'), ('AF', 'AttenteFormateur'), ('RF', 'RefusFormateur'), ('VC', 'ValidationClient'), ('AC', 'AttenteClient'), ('RC', 'RefusClient')], default='AF', max_length=20),
        ),
    ]
