# Generated by Django 2.0.5 on 2018-07-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0003_auto_20180716_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='Type_vehicule',
            field=models.CharField(choices=[('voiture', 'Voiture'), ('moto', 'Moto'), ('velo', 'Velo')], default=('voiture', 'Voiture'), max_length=10),
        ),
    ]
