# Generated by Django 2.0.5 on 2018-07-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0003_auto_20180716_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='Statut',
            field=models.CharField(choices=[('VF', 'ValidationFormateur'), ('AF', 'AttenteFormateur'), ('RF', 'RefusFormateur'), ('AD', 'AttenteDevis')], default='AD', max_length=20),
        ),
    ]
