# Generated by Django 2.0.5 on 2018-07-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0005_remove_vehicule_type_vehicule'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='Type_vehicule',
            field=models.CharField(choices=[('VOITURE', 'Voiture'), ('MOTO', 'Moto'), ('VELO', 'Velo')], default=('VOITURE', 'Voiture'), max_length=10),
        ),
    ]
