# Generated by Django 2.0.5 on 2018-07-16 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0006_vehicule_type_vehicule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicule',
            name='Type_vehicule',
        ),
    ]
